trim_galore: 
  - "--illumina" #Illumina adapter
  - "--quality 20" #Phred score
  # Don't run with `--fastqc` flag

quast:
  - "--min-contig 10" #Lower threshold for a contig length (in bp)

prokka:
  - "--prefix mygenome" #Filename output prefix [auto] (default '')
  # Don't run with `-outdir` flag 